# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './gui/markov.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(969, 832)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.glCentral = QtWidgets.QGridLayout(self.centralwidget)
        self.glCentral.setObjectName("glCentral")
        self.glMain = QtWidgets.QGridLayout()
        self.glMain.setObjectName("glMain")
        self.twResult = QtWidgets.QTableWidget(self.centralwidget)
        self.twResult.setObjectName("twResult")
        self.twResult.setColumnCount(0)
        self.twResult.setRowCount(0)
        self.glMain.addWidget(self.twResult, 4, 0, 2, 4)
        self.lblNum = QtWidgets.QLabel(self.centralwidget)
        self.lblNum.setObjectName("lblNum")
        self.glMain.addWidget(self.lblNum, 1, 0, 1, 2)
        self.cbGeneration = QtWidgets.QCheckBox(self.centralwidget)
        self.cbGeneration.setObjectName("cbGeneration")
        self.glMain.addWidget(self.cbGeneration, 1, 3, 1, 1)
        self.lblMatrix = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblMatrix.setFont(font)
        self.lblMatrix.setObjectName("lblMatrix")
        self.glMain.addWidget(self.lblMatrix, 0, 0, 1, 3)
        self.btnSetMatrix = QtWidgets.QPushButton(self.centralwidget)
        self.btnSetMatrix.setObjectName("btnSetMatrix")
        self.glMain.addWidget(self.btnSetMatrix, 0, 3, 1, 1)
        self.lblResult = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblResult.setFont(font)
        self.lblResult.setObjectName("lblResult")
        self.glMain.addWidget(self.lblResult, 3, 0, 1, 2)
        self.lblAuthor = QtWidgets.QLabel(self.centralwidget)
        self.lblAuthor.setStyleSheet("background-color: rgb(220, 220, 220);\n"
"color: rgb(110, 110, 110);")
        self.lblAuthor.setObjectName("lblAuthor")
        self.glMain.addWidget(self.lblAuthor, 6, 0, 1, 4)
        self.twMatrix = QtWidgets.QTableWidget(self.centralwidget)
        self.twMatrix.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.twMatrix.setObjectName("twMatrix")
        self.twMatrix.setColumnCount(0)
        self.twMatrix.setRowCount(0)
        self.glMain.addWidget(self.twMatrix, 2, 0, 1, 4)
        self.btnGraphic = QtWidgets.QPushButton(self.centralwidget)
        self.btnGraphic.setObjectName("btnGraphic")
        self.glMain.addWidget(self.btnGraphic, 3, 3, 1, 1)
        self.btnCacl = QtWidgets.QPushButton(self.centralwidget)
        self.btnCacl.setObjectName("btnCacl")
        self.glMain.addWidget(self.btnCacl, 3, 2, 1, 1)
        self.sbNum = QtWidgets.QSpinBox(self.centralwidget)
        self.sbNum.setMinimum(1)
        self.sbNum.setMaximum(10)
        self.sbNum.setObjectName("sbNum")
        self.glMain.addWidget(self.sbNum, 1, 2, 1, 1)
        self.glCentral.addLayout(self.glMain, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Маслова Марина ИУ7-73Б Лабораторная работа №2"))
        self.lblNum.setText(_translate("MainWindow", "Количество состояний системы"))
        self.cbGeneration.setText(_translate("MainWindow", "Генерация"))
        self.lblMatrix.setText(_translate("MainWindow", "Матрица интенсивностей переходов"))
        self.btnSetMatrix.setText(_translate("MainWindow", "Задать"))
        self.lblResult.setText(_translate("MainWindow", "Результат"))
        self.lblAuthor.setText(_translate("MainWindow", "Автор: Маслова Марина ИУ7-73Б"))
        self.btnGraphic.setText(_translate("MainWindow", "Показать график"))
        self.btnCacl.setText(_translate("MainWindow", "Рассчитать"))
